### ISSUE TITLE
Author processing script adding \bigskip

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/documents#69]
@jouvin I see that with your [last changes](https://github.com/HSF/documents/commit/c38b880f78ea78d51e25968410bf180246baeef8) to `a2tex.py` you added a `\bigskip` to the output between each line of the institutions. This seems like very unnecessary space and it makes the institution list grow from 3.5 pages to 6.

Was there a good reason for this or can we revert?

P.S. I [reviewed](https://github.com/HSF/documents/pull/57) this, so I am also to blame for not noticing!

**Comment by jouvin** [comment]
@graeme-a-stewart sorry for the mistake! Fix underway...
