### ISSUE TITLE
Some issues with JHEP output

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/documents#73]
I found that the JHEP author output made a few mistakes - there was no separator between the author's names and the order was wrong (should be "Forename Surname"). Getting the commas and final "and Author X" correct is quite fiddly.

There is a fix for that in #72.

One other issue though is that no footnotes are printed in the JHEP styled output. Most papers like to at least identify the editors and other authors will want their grants acknowledged.

**Comment by jouvin** [comment]
@graeme-a-stewart another mistake of mine... When I started the generation of JHEP format, I had no clear idea whether it was important or not to have them. But it should be pretty easy to add with `\note`.
